### ISSUE TITLE
pygame.error: Couldn't find glyph

### ISSUE THREAD

**Issue by celikmustafa89** [CodeAccelerando/Matrix-Rain-An-Image#2]
I am getting following error when I run this code `python src/main.py images/garf.jpg`

```pygame 2.0.3 (SDL 2.0.16, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/celik/codes/oak/Matrix-Rain-An-Image/src/main.py", line 159, in <module>
    main()
  File "/Users/celik/codes/oak/Matrix-Rain-An-Image/src/main.py", line 101, in main
    symbol_list, symbol_columns = get_symbols(img)
  File "/Users/celik/codes/oak/Matrix-Rain-An-Image/src/main.py", line 46, in get_symbols
    symbol_list.append(Symbol(x, y, 0, pygame.Color("white")))
  File "/Users/celik/codes/oak/Matrix-Rain-An-Image/src/symbol.py", line 28, in __init__
    self.charSet = [font.render(char, True, color) for char in katakana]
  File "/Users/celik/codes/oak/Matrix-Rain-An-Image/src/symbol.py", line 28, in <listcomp>
    self.charSet = [font.render(char, True, color) for char in katakana]
pygame.error: Couldn't find glyph```

**Comment by jarheadjoe** [comment]
same issue here

**Comment by iZucked** [comment]
Just got around to fixing this with [this commit](https://github.com/iZucked/Matrix-Rain-An-Image/commit/6d318e5a0e51913414006173040aeea527780c47), thanks for reporting this!
